### ISSUE TITLE
Make all lanes in crazy notes autonomous

### ISSUE THREAD

**Issue by GoogleCodeExporter** [raynebc/editor-on-fire#211]
```
I was doing a quick bit of testing for the new PART KEYS handling, and I find 
that if I use grid snap to drag one note to the start position of another note, 
one of the notes' tails is changed to match the length of the other note.  
Notes in the non pro keys track need to be able to freely overlap and have 
independent lengths.

Another complication is how to change the length of one note but not the others 
if it is a chord, because all the notes' lengths are changed.
```

Original issue reported on code.google.com by `raynebc` on 28 Nov 2010 at 3:50

**Comment by raynebc** [comment]
Commits 6a081d448ca2f7c0e3aee3c1ff19b167fb9336ac and 8095e7692c296540a19c0db7975ff4a9f2839460 implemented a new "disjointed" status that allows different gems of the same chord to have different lengths, by keeping affected notes as a single gem per note.  The disjointed status is copied to all notes at the same position, but it hasn't been determined yet whether all disjointed notes at the same position should forcibly share all statuses.

**Comment by raynebc** [comment]
For now I probably won't mandate that they all collectively share the same status flags (except disjointed status), but limitations in MIDI export will probably result in all gems in a disjointed chord generally getting the same statuses (ie. all disjointed gems falling within the span of a status marker get affected, and markers are not per-lane).
