### ISSUE TITLE
Mac version - clicking outside EOF freezes app

### ISSUE THREAD

**Issue by GoogleCodeExporter** [raynebc/editor-on-fire#286]
```
What steps will reproduce the problem?
1. click anywhere outside the EOF window while EOF is open

What is the expected output? What do you see instead?

Clicking anywhere outside the EOF window freezes it, and it must be force-quit, 
then relaunched.

What version of the product are you using? On what operating system?

EOF 1.71 with Mac OS X Mavericks

Please provide any additional information below.

I've used EOF for at least 2 years, and it's been an issue with the Mac port 
from the start. Surprised it hasn't been addressed by now tbh.
```

Original issue reported on code.google.com by `tristan....@gmail.com` on 12 Sep 2014 at 11:36

**Comment by th1rtyf0ur** [comment]
just saw this in the 'closed' section- I do notice that in some cases when I click outside the app, then click back in, the arrows & other keys will work, but the mouse doesn't seem to work- nothing highlights on mouseover or is selected with clicks unless I move the whole window by its title bar, then it works again. *shrug* I'm guessing it's an allegro issue.

**Comment by raynebc** [comment]
Unfortunately I'll have no ability to debug anything outside of the Windows platform.  If you do find a Mac-specific defect and have a way to fix it, we can get it added.
