### ISSUE TITLE
allow vertical chord boxes in arpeggio/handshape by setting chordId in handShapes section

### ISSUE THREAD

**Issue by th1rtyf0ur** [raynebc/editor-on-fire#292]
Allow handshape/arpeggio to include sub-chords with bounding vertical boxes by setting handShape chordId to the first chord in the handshape/arpeggio. For "cleanest" display ensure 'crazy' (sustain) is off (unless user specified? i.e. allow disabling crazy mode inside a handshape in EOF?) and set chordName/displayName for sub-chords inside the shape to empty string.

For more details see discussion at http://customsforge.com/topic/22596-handshapearpeggio-for-multiple-notes-at-a-time/

**Comment by raynebc** [comment]
Implemented in 3f6f6b8dea1f3b19133ca1600860156579fb634f
