### ISSUE TITLE
allow slashes in chord names (enhancement)

### ISSUE THREAD

**Issue by th1rtyf0ur** [raynebc/editor-on-fire#295]
I tried making a chord named Bb/A and it gave me a warning about "unaccepted characters". I've seen slashes in official DLC before, so I manually edited the XML & confirmed that it in fact does not crash RS. :) Timing the screenshot was a bit off, but there's a slash visible in the very foreground (half behind the headstock), and another way in the back.

![screen shot 2015-11-11 at 4 57 23 pm](https://cloud.githubusercontent.com/assets/6560566/11087082/7ca5516e-889a-11e5-984a-c6c78189652e.png)

**Comment by raynebc** [comment]
I fixed this in my local code repository several days ago.  I've committed it just now with 5c269195f7bc989aaef267a1fd5d6836a6698287

**Comment by th1rtyf0ur** [comment]
confirmed, thanks!
