### ISSUE TITLE
MIDI Instruments Values starts from the 0.

### ISSUE THREAD

**Issue by L0FKA** [raynebc/editor-on-fire#298]
In Eof config file midi instruments set using table like this: https://www.midi.org/specifications/item/gm-level-1-sound-set

which starts from 1 element, but eof addressing those list from 0 element

so it's actually not a Guitar harmoonicsat 32, it's at 31
I'd suggest change eof's logic for handling this, or maybe we should just go with obvious workaround and do oldschool with 0 as first element-lists (aka arrays)?

Thanks :)

**Comment by raynebc** [comment]
Thanks, I've fixed this for the next commit.  For now I'm going with having EOF decrement the number internally so the user would define instrument 32 for "Guitar harmonics" as expected.
