### ISSUE TITLE
Rocksmith Import button disabled

### ISSUE THREAD

**Issue by IlGuru** [raynebc/editor-on-fire#299]
I can't import xml files because the button under File menu is disabled.
How can I activate it?

![bug](https://cloud.githubusercontent.com/assets/14052045/26763170/7ad808a6-494e-11e7-80bc-cc742ba95bb2.PNG)

**Comment by raynebc** [comment]
You need to be in one of the "REAL" guitar or bass tracks to be able to import Guitar Pro tab or Rocksmith arrangements.

**Comment by IlGuru** [comment]
Thank you sir!
