### ISSUE TITLE
Ctrl-X shouldn't set the fret number to "X"

### ISSUE THREAD

**Issue by colejohnson66** [raynebc/editor-on-fire#301]
When I use Ctrl-X on a note, it shouldn't change the fret number to "X" (at least for Rocksmith). This causes all dead notes to show up as dead open notes in the game, which is not correct.

**Comment by raynebc** [comment]
This is not a bug.  By design, CTRL+X removes all fret numbering and sets dead notes as per Rock Band 3 usage.  If you want to toggle string mutes, use SHIFT+X instead, which leaves the defined fret numbering and fingering in place.
