### ISSUE TITLE
Understand drop tunings

### ISSUE THREAD

**Issue by colejohnson66** [raynebc/editor-on-fire#302]
Editor on Fire correctly recognizes Drop D tuning and Eb tuning, but fails to recognize Eb drop Db (D# drop C#) or lower. It also fails to recognize D standard or lower. The detection should changed to something like this:

```
if (all offsets == 0)
  E std;              //  0  0  0  0 => E std

if (all offsets but low 0 && low == -2)
  Drop D;             //  0  0  0 -2 => Drop D

if (all offsets the same)
  {low} std;          // -2 -2 -2 -2 => D std

if (all offsets but low the same && low is 2 lower than others)
  {low+2} Drop {low}; // -1 -1 -1 -3 => Eb Drop Db
```

**Comment by raynebc** [comment]
EOF wasn't intended to list a name for every possible tuning, just some of the most common ones.

**Comment by raynebc** [comment]
Completed in commit 4298684.
