### ISSUE TITLE
Rocksmith Import fails to import arrangements with oblique bends

### ISSUE THREAD

**Issue by sswires** [raynebc/editor-on-fire#307]
Hey,

Pretty simple issue, I've tried this with two CDLCs that have olique bends and I imagine official DLC is also the same. The following gets printed to the log:

```
704: 	Placed bend tech note at 193733ms
704: 					Added 75 notes
704: 				Processing <anchors> tag on line #5844
704: 					Added 33 anchors
704: 			Processing <level> tag on line #5882
704: 				Processing <notes> tag on line #5883
704: 					Added 169 notes
704: 				Processing <chords> tag on line #6054
704: 	Placed bend tech note at 176470ms
704: 					Error:  Cannot find tech notes for chord at 175042ms.  Aborting
```

An example of another failed import looks like the following:

```
      <chord time="235.426" linkNext="0" accent="0" chordId="3" fretHandMute="0" highDensity="0" ignore="0" palmMute="0" hopo="0" strum="down">
        <chordNote time="235.426" linkNext="0" accent="0" bend="2" fret="16" hammerOn="0" harmonic="0" hopo="0" ignore="0" leftHand="1" mute="0" palmMute="0" pluck="-1" pullOff="0" slap="-1" slideTo="-1" string="3" sustain="1.091" tremolo="0" harmonicPinch="0" pickDirection="0" rightHand="-1" slideUnpitchTo="-1" tap="0" vibrato="0">
          <bendValues>
            <bendValue time="235.426" step="2" unk5="0" />
          </bendValues>
        </chordNote>
        <chordNote time="235.426" linkNext="0" accent="0" bend="0" fret="14" hammerOn="0" harmonic="0" hopo="0" ignore="0" leftHand="3" mute="0" palmMute="0" pluck="-1" pullOff="0" slap="-1" slideTo="-1" string="4" sustain="0" tremolo="0" harmonicPinch="0" pickDirection="0" rightHand="-1" slideUnpitchTo="-1" tap="0" vibrato="0" />
      </chord>
```

I can send over the arrangement file if you need to debug this.

Thanks.

**Comment by raynebc** [comment]
Does this happen with the 2-20-2019 hotfix?  It's best if I have an XML file to test with, so I can reliably reproduce the problem.

**Comment by sswires** [comment]
I have tested the hotfix and appears to have the same result. I have attached an affected CDLC arrangement file.

[foofightersallmylife_lead.zip](https://github.com/raynebc/editor-on-fire/files/2952790/foofightersallmylife_lead.zip)

**Comment by raynebc** [comment]
It should be fixed with commit 2c308f9b293e952103ffef133b9c1eecc27fe3dc.  Here's a beta Windows build if you wanted to try it:
http://ignition.customsforge.com/eof/download/309

**Comment by sswires** [comment]
I have tested the above build with 2 affected arrangements and they appear to import just fine. I will also note that for tracks with DD, the maximum difficulty does not appear to show all notes. This maybe due to to the way Rocksmith stores difficulty levels combined with the maximum difficulty from each section.

Thanks for the quick fix.

**Comment by raynebc** [comment]
That is how Rocksmith's dynamic difficulty system is designed.  Each difficulty defines changes to the prior difficulty, so they are additive.  You can change to the highest difficulty in the example arrangement (11) and use the "Track>Rocksmith>Flatten this difficulty" function to make it so that difficulty 11 has the entire arrangement with all 950 notes.
