### ISSUE TITLE
Most Rocksmith CDLC Files Fail to Import

### ISSUE THREAD

**Issue by FolkSong** [raynebc/editor-on-fire#312]
I sometimes like to fix up Rocksmith CDLC files from Customsforge. After unpacking the CDLC using the Rocksmith Custom Song Toolkit, I try to import the XML file into a new EOF project. Most of the time I get an error message telling me to check the log. The error in the log is "Error reading sustain time on line #867" or similar.

Looking at the XML file, the line in question will be the first note not to have a sustain value specified. Eg. here is a snippet of a file I'm looking at:
```
    <levels count="1">
        <level difficulty="0">
            <notes count="392">
                <note time="10.913" string="1" fret="0" sustain="0.346"/>
                <note time="11.375" string="1" fret="2" sustain="0.346"/>
                <note time="11.836" string="1" fret="3" sustain="0.814"/>
                <note time="12.766" string="0" fret="3" sustain="0.814"/>
                <note time="13.697" string="1" fret="3" sustain="0.814"/>
                <note time="14.627" string="1" fret="3" sustain="0.349"/>
                <note time="15.092" string="1" fret="2" sustain="0.349"/>
                <note time="15.557" string="1" fret="0" sustain="0.814"/>
                <note time="16.487" string="0" fret="0" sustain="0.814"/>
                <note time="17.418" string="1" fret="0" sustain="0.820"/>
                <note time="18.355" string="1" fret="0" sustain="0.352"/>
                <note time="18.824" string="1" fret="2"/>
```
The last line is the one with the error. If I manually add a small sustain, the error moves on to the next line without one. If I manually add a sustain to every note, the file imports successfully. No other problems after that point, I can make my changes and pack it back into a valid CDLC.

It seems EOF won't accept notes with no sustain, but Rocksmith itself does accept them and the common CDLC creation tools write files that way.

**Comment by raynebc** [comment]
You're probably using a very old version of EOF.  If you haven't applied the hotfix, your (presumably) Windows build is several years old and not supportive of the abridged XML format the toolkit developers and I came up with (where unused XML fields for a note can be omitted instead of being defined needlessly with default values).  Please retry after having applied the 9-26-2020 hotfix and if it doesn't work, send me the EOF log and ideally the XML file in question.

**Comment by FolkSong** [comment]
Ah, thank you. I had the last "release" version but didn't see the hotfix. Everything looks good now.
