### ISSUE TITLE
Importing Rocksmith bass arrangement fails very often. Song works fine in Rocksmith.

### ISSUE THREAD

**Issue by Seda145** [raynebc/editor-on-fire#322]
`
300: 	Processing line #591
300: 	Processing line #592
300: 		Processing <levels> tag on line #592
300: 			Processing <level> tag on line #593
300: 				Processing <notes> tag on line #594
300: 					Added 28 notes
300: 				Processing <anchors> tag on line #625
300: 					Added 17 anchors
300: 			Processing <level> tag on line #646
300: 				Processing <notes> tag on line #647
300: 	Error reading sustain time on line #669.  Aborting
300: eof_switch_out_callback() entered

`

It seems sustains are required for the xml to be parsed properly.
[XML file.zip](https://github.com/raynebc/editor-on-fire/files/13593993/XML.file.zip)

**Comment by raynebc** [comment]
I tested it in the last released hotfix of EOF (9-26-2020) and it imports the XML file without error.  Make sure to download the patched version, which looks like it's still available to download from here:
https://ignition4.customsforge.com/eof

An old enough version of EOF won't correctly assume there is no sustain when it isn't defined for a note in the abridged XML format.
